### ISSUE TITLE
Guided Timer 

### ISSUE THREAD

**Issue by minikin** [HighVibe/hvn#364]
Check [Guided Timer Complete Overview](https://github.com/HighVibe/hvn/issues/287) for full details.
- [ ] Create new Guided Timer Preset #351
- [ ] Implement Interval Editing for GT #361
- [ ] Allow preview and select background tracks for GT #360 
- [ ] Integrate Guided Timer Preset Creation with Firebase + mobx #354
- [ ] Edit GT preset #362
- [ ] Implement UI of GT in running mode. #359
- [ ] Display list of available Guided Timers (Presets) #355
- [ ] Integrate Guided Timers (Presets) with Firebase + mobx #356
- [ ] Save history of running timers and display it a list + Firebase/mobx #363
- [ ] Keep phone screen active while GT is running #357
- [ ] Play background sounds/music while the phone is locked and GT is running #358
